# Generated by Django 4.2.16 on 2025-08-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
