# Generated by Django 4.2.16 on 2025-08-13 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carhire', '0002_alter_payment_paystack_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
